#!/bin/bash
# Moodle Container Entrypoint
# Generates config.php from environment variables, then starts cron + Apache
# All credentials are injected via environment variables at runtime — never hardcoded
# Environment variables expected (set by ECS task definition from Secrets Manager):
#   MOODLE_DB_HOST, MOODLE_DB_NAME, MOODLE_DB_USER, MOODLE_DB_PASS, MOODLE_DB_PORT
#   MOODLE_SESSION_CACHE_ENDPOINT, MOODLE_MUC_CACHE_ENDPOINT
#   MOODLE_WWWROOT, MOODLE_DATAROOT, MOODLE_ADMIN_EMAIL

set -e

echo "[entrypoint] Starting Moodle container"

# Ensure EFS-mounted directories have correct ownership
for dir in /var/www/moodle/data /var/www/moodle/cache /var/www/moodle/temp; do
    if [ -d "$dir" ]; then
        chown -R www-data:www-data "$dir" 2>/dev/null || true
    fi
done

# Ensure local ephemeral directories exist and are writable
mkdir -p /var/www/moodle/local/opcache
chown -R www-data:www-data /var/www/moodle/local

# Set OPcache memory from environment variable (default: 512 MB)
OPCACHE_MEMORY_CONSUMPTION="${OPCACHE_MEMORY_CONSUMPTION:-512}"
export OPCACHE_MEMORY_CONSUMPTION
echo "[entrypoint] OPcache memory: ${OPCACHE_MEMORY_CONSUMPTION}M"

# --- Generate Moodle config.php from environment variables ---
echo "[entrypoint] Generating config.php"

# Defaults
MOODLE_WWWROOT="${MOODLE_WWWROOT:-https://localhost}"
MOODLE_DATAROOT="${MOODLE_DATAROOT:-/var/www/moodle/data}"
MOODLE_DB_TYPE="${MOODLE_DB_TYPE:-auroramysql}"
MOODLE_DB_HOST="${MOODLE_DB_HOST:-localhost}"
MOODLE_DB_PORT="${MOODLE_DB_PORT:-3306}"
MOODLE_DB_NAME="${MOODLE_DB_NAME:-moodle}"
MOODLE_DB_USER="${MOODLE_DB_USER:-moodle}"
MOODLE_DB_PASS="${MOODLE_DB_PASS:-}"
MOODLE_DB_PREFIX="${MOODLE_DB_PREFIX:-mdl_}"

# Parse session cache endpoint (host:port)
SESSION_CACHE_HOST="${MOODLE_SESSION_CACHE_ENDPOINT%%:*}"
SESSION_CACHE_PORT="${MOODLE_SESSION_CACHE_ENDPOINT##*:}"
# Ensure port is numeric, default to 6379
SESSION_CACHE_PORT=$(echo "${SESSION_CACHE_PORT}" | tr -dc '0-9')
SESSION_CACHE_PORT="${SESSION_CACHE_PORT:-6379}"

# Parse MUC cache endpoint (host:port)
MUC_CACHE_HOST="${MOODLE_MUC_CACHE_ENDPOINT%%:*}"
MUC_CACHE_PORT="${MOODLE_MUC_CACHE_ENDPOINT##*:}"
MUC_CACHE_PORT=$(echo "${MUC_CACHE_PORT}" | tr -dc '0-9')
MUC_CACHE_PORT="${MUC_CACHE_PORT:-6379}"

cat > /var/www/moodle/html/config.php << MOODLE_CONFIG
<?php
// Moodle configuration file — auto-generated by entrypoint.sh
// Do NOT edit manually. All values come from ECS environment variables.
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

// --- Database ---
\$CFG->dbtype    = '${MOODLE_DB_TYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DB_HOST}';
\$CFG->dbname    = '${MOODLE_DB_NAME}';
\$CFG->dbuser    = '${MOODLE_DB_USER}';
\$CFG->dbpass    = '${MOODLE_DB_PASS}';
\$CFG->prefix    = '${MOODLE_DB_PREFIX}';
\$CFG->dboptions = array(
    'dbport'     => ${MOODLE_DB_PORT},
    'dbcollation' => 'utf8mb4_unicode_ci',
    'dbcompressedrows' => false,
);

// --- Paths ---
\$CFG->wwwroot   = '${MOODLE_WWWROOT}';
\$CFG->dataroot  = '${MOODLE_DATAROOT}';
\$CFG->directorypermissions = 02777;
\$CFG->admin     = 'admin';

// --- Local cache (ephemeral, per-task) ---
\$CFG->localcachedir = '/var/www/moodle/local';
\$CFG->tempdir       = '/var/www/moodle/temp';
\$CFG->cachedir      = '/var/www/moodle/cache';

// --- Session handling via Redis/Valkey (ElastiCache Serverless with TLS) ---
\$CFG->session_handler_class = '\core\session\redis';
\$CFG->session_redis_host = '${SESSION_CACHE_HOST}';
\$CFG->session_redis_port = ${SESSION_CACHE_PORT};
\$CFG->session_redis_database = 0;
\$CFG->session_redis_prefix = 'moodle_sess_';
\$CFG->session_redis_acquire_lock_timeout = 120;
\$CFG->session_redis_lock_expire = 7200;
\$CFG->session_redis_serializer_use_igbinary = false;
// Enable TLS encryption for ElastiCache Serverless (required)
\$CFG->session_redis_encrypt = ['verify_peer' => false, 'verify_peer_name' => false];

// --- Reverse proxy (ALB / CloudFront) ---
// Note: reverseproxy is NOT set because mod_remoteip already handles
// X-Forwarded-For at the Apache level (replacing REMOTE_ADDR), which
// removes the header before PHP sees it. Setting reverseproxy=true
// would cause Moodle to reject requests when X-Forwarded-For is absent.
\$CFG->sslproxy     = true;

// --- Performance ---
\$CFG->cachejs = true;
\$CFG->langstringcache = true;
\$CFG->themedesignermode = false;

// --- Security ---
\$CFG->passwordpolicy = true;
\$CFG->cronclionly = true;
\$CFG->cronremotepassword = '';

require_once(__DIR__ . '/lib/setup.php');
MOODLE_CONFIG

chown www-data:www-data /var/www/moodle/html/config.php
chmod 640 /var/www/moodle/html/config.php
echo "[entrypoint] config.php generated successfully"

# --- Run Moodle CLI install if database is empty ---
# Check if Moodle tables exist; if not, run the installer
echo "[entrypoint] Checking if Moodle needs installation..."
INSTALL_CHECK=$(php -r "
\$conn = new mysqli('${MOODLE_DB_HOST}', '${MOODLE_DB_USER}', '${MOODLE_DB_PASS}', '${MOODLE_DB_NAME}', ${MOODLE_DB_PORT});
if (\$conn->connect_error) { echo 'CONN_ERROR'; exit(0); }
\$result = \$conn->query(\"SHOW TABLES LIKE '${MOODLE_DB_PREFIX}user'\");
echo (\$result && \$result->num_rows > 0) ? 'INSTALLED' : 'NEEDS_INSTALL';
\$conn->close();
" 2>&1)

if [ "$INSTALL_CHECK" = "NEEDS_INSTALL" ]; then
    # Clean up any leftover tables from a previous failed install
    echo "[entrypoint] Cleaning up any leftover tables..."
    php -r "
\$conn = new mysqli('${MOODLE_DB_HOST}', '${MOODLE_DB_USER}', '${MOODLE_DB_PASS}', '${MOODLE_DB_NAME}', ${MOODLE_DB_PORT});
if (\$conn->connect_error) { exit(0); }
\$conn->query('SET FOREIGN_KEY_CHECKS = 0');
\$result = \$conn->query('SHOW TABLES');
while (\$row = \$result->fetch_row()) { \$conn->query('DROP TABLE IF EXISTS \`' . \$row[0] . '\`'); }
\$conn->query('SET FOREIGN_KEY_CHECKS = 1');
\$conn->close();
" 2>&1
    echo "[entrypoint] Running Moodle CLI installer..."
    if php /var/www/moodle/html/admin/cli/install_database.php \
        --agree-license \
        --fullname="ECV Learning Solutions" \
        --shortname="ECV LMS" \
        --adminuser=admin \
        --adminpass=Changeme123! \
        --adminemail="${MOODLE_ADMIN_EMAIL:-admin@ecvth.com}" \
        2>&1; then
        echo "[entrypoint] Moodle installation complete"
    else
        echo "[entrypoint] WARNING: install_database.php failed — dropping all tables and retrying..."
        # Drop all Moodle tables so next attempt starts clean
        php -r "
\$conn = new mysqli('${MOODLE_DB_HOST}', '${MOODLE_DB_USER}', '${MOODLE_DB_PASS}', '${MOODLE_DB_NAME}', ${MOODLE_DB_PORT});
if (\$conn->connect_error) { echo 'Cannot connect to drop tables'; exit(1); }
\$conn->query('SET FOREIGN_KEY_CHECKS = 0');
\$result = \$conn->query('SHOW TABLES');
while (\$row = \$result->fetch_row()) { \$conn->query('DROP TABLE IF EXISTS ' . \$row[0]); }
\$conn->query('SET FOREIGN_KEY_CHECKS = 1');
echo 'All tables dropped';
\$conn->close();
" 2>&1
        echo "[entrypoint] Retrying Moodle CLI installer..."
        php /var/www/moodle/html/admin/cli/install_database.php \
            --agree-license \
            --fullname="ECV Learning Solutions" \
            --shortname="ECV LMS" \
            --adminuser=admin \
            --adminpass=Changeme123! \
            --adminemail="${MOODLE_ADMIN_EMAIL:-admin@ecvth.com}" \
            2>&1 || echo "[entrypoint] WARNING: Retry also failed — manual intervention may be needed"
        echo "[entrypoint] Moodle installation retry complete"
    fi
elif [ "$INSTALL_CHECK" = "CONN_ERROR" ]; then
    echo "[entrypoint] WARNING: Could not connect to database — Moodle may fail to start"
else
    echo "[entrypoint] Moodle already installed, skipping CLI install"
fi

# --- Purge theme cache on startup ---
# Ensures stale cached CSS/JS with wrong hostnames are regenerated
echo "[entrypoint] Purging Moodle caches..."
php /var/www/moodle/html/admin/cli/purge_caches.php 2>&1 || echo "[entrypoint] WARNING: Cache purge failed (may be first boot)"

# Start the Moodle cron runner in the background
/usr/local/bin/moodle-cron.sh &
CRON_PID=$!
echo "[entrypoint] Cron runner started (PID: ${CRON_PID})"

# Trap signals for graceful shutdown
cleanup() {
    echo "[entrypoint] Shutting down..."
    kill "${CRON_PID}" 2>/dev/null || true
    apachectl graceful-stop 2>/dev/null || true
    exit 0
}
trap cleanup SIGTERM SIGINT SIGQUIT

echo "[entrypoint] Starting Apache"
exec apache2-foreground
